# Golang CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/yosuke-furukawa/programming-go-study
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get golang.org/x/net/html
      - run: go get github.com/golang/lint/golint
      - run: (! gofmt -s -d . | grep '^')
      - run: golint ./...
      - run: go vet -v ./...
      - run: go test -race -v ./{ch01,ch02,ch03,ch04,ch05,ch06,ch07}/...
